# Generated by Django 6.0.5 on 2026-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_intern_expired',
            field=models.BooleanField(default=False, verbose_name='Estágio Expirado'),
        ),
    ]
