# Generated by Django 6.0.5 on 2026-06-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_intern_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular da Conta'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='channel_type',
            field=models.CharField(default='KWANZA', max_length=20, verbose_name='Canal de Saque'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='crypto_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Cripto'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='usdt_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rede USDT'),
        ),
    ]
